services:
  orcherstrator:
    build: "./orchestrator"
    ports:
      - "80:4000"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    
  service-user:
    build: "./services/users"
    ports:
      - "8002:4002"
    environment:
       MONGO_CONNECT: ${MONGO_CONNECT}


  service-app:
    build: "./services/app"
    ports:
      - "8001:4001"
    environment:
      NODE_ENV : ${NODE_ENV}
      DATABASE_URL : ${DATABASE_URL}